---
# tasks file for ansible-freeipa-client

- name: Assert supported platform
  tags: assertion
  assert:
    that: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7') or
          (ansible_distribution == 'Fedora' and ansible_distribution_major_version == '22') or
          ansible_distribution_release == 'trusty'

- name: Import variables
  tags: import
  include_vars: "{{ ansible_distribution }}.yml"

- name: Set DNS server
  tags: dns
  become: true
  when: dns_server is defined
  lineinfile:
    state=present
    regexp='^nameserver.+'
    line="nameserver {{ dns_server }}"
    dest=/etc/resolv.conf

- name: Update cache
  tags: packagemanagement
  become: true
  when: ansible_pkg_mgr  == 'apt'
  action: "{{ ansible_pkg_mgr }} update_cache=yes"

- name: Install required packages
  tags: packagemanagement
  become: true
  with_items: packages
  action: "{{ ansible_pkg_mgr }} state=installed name={{ item }}"

- name: Check if host is enrolled
  tags: enroll
  register: ipaconf
  stat:
    path=/etc/ipa/default.conf

- name: Enroll host in domain
  tags: enroll
  become: true
  when: not ipaconf.stat.exists
  command: "{{ ipa_install_command }}
          --server={{ server }}
          --domain={{ domain }}
          --principal={{ enroll_user }}
          --password={{ enroll_pass }}
          --ssh-trust-dns
          --mkhomedir
          --enable-dns-updates
          --unattended

- name: Include Ubuntu specific tasks
  tags: ubuntu
  when: ansible_distribution_release == 'trusty'
  include: ubuntu.yml
